<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3uqVHVu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3uqVHVu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3uqVHVu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3uqVHVu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3uqVHVu\App_KernelDevDebugContainer([
    'container.build_hash' => '3uqVHVu',
    'container.build_id' => '599adedd',
    'container.build_time' => 1582017136,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3uqVHVu');
